### ISSUE TITLE
everything works BUT slowmovie...

### ISSUE THREAD

**Issue by weow147** [hogit/slow-movie#1]
hogit:  i've got the IT8951 tests working... but i'm getting the following when i run slowmovie.py
`ImportError: cannot import name 'img_manip' from 'IT8951'`
any thoughts?

solved - i had a duplicate folder name or something whack with IT8951.

I appreciate your work on this - i've got a 10.3 in epaper working perfectly!!!!!

**Comment by j2r2jones** [comment]
I'm having a similar issue:

Traceback (most recent call last):
  File "/home/pi/SlowMovie/slowmovie.py", line 29, in <module>
    from IT8951.display import AutoEPDDisplay
  File "/home/pi/SlowMovie/IT8951/display.py", line 6, in <module>
    from . import img_manip
ImportError: cannot import name 'img_manip' from 'IT8951' (/home/pi/SlowMovie/IT8951/__init__.py)

How did you end up solving this?

**Comment by weow147** [comment]
howdy j2... i'm not sure what you've got going on there.  In my case the install process got messy and I wound up with the IT8951 folder in a few different locations.

Try renaming all the IT8951 folders you DONT NEED (like xIT8951 or similar).  What working for me is one IT8951 folder in /home/pi.  I renamed the other one to /home/pi/slow-movie/xIT8951.  Try that and let me know.

**Comment by j2r2jones** [comment]
Yes! Ok this worked for me as well. One thing I'll add: Do not use the curl command / automated install from TomWhitwell/SlowMovie.

Thank you very much!

**Comment by weow147** [comment]
awesome - so glad you got it running.  Mine seems to freeze every once in awhile.  Not sure how to debug it, easiest to just powercycle until i find some time.

**Comment by j2r2jones** [comment]
I'm not sure if this will help your issue but worth stating here for documentation  --

The Waveshare drivers were causing all kinds of weird issues with the SPI for me. I ended up wiping raspbian and doing a fresh install with only IT8951 and that helped me out.

**Comment by j2r2jones** [comment]
Also see this bug report: https://github.com/TomWhitwell/SlowMovie/issues/115#issue-1145699320
"The reason is that the for-loop in line 182 uses a wrong result variable named outputGuess instead of output:

for length, outputGuess in [(days, "d"), (hours, "h"), (minutes, "m"), (seconds, "s")]:

If the calculated seconds is 1 or below, the loop runs to the end and the variable output keeps the value "guess".

The subsequent if-block steps to line 196 (call stack see below)

Changing the line 182 to the following line fixes the error:
for length, output in [(days, "d"), (hours, "h"), (minutes, "m"), (seconds, "s")]
"
